#include "prowsetk/plugins/scrape2postman.hpp"
#include "prowsetk/url.hpp"

#include <algorithm>
#include <cmath>
#include <fstream>
#include <locale>
#include <map>
#include <sstream>

namespace prowsetk::plugins::scrape2postman {
namespace {

std::string quote(std::string_view value) {
    constexpr char hex[] = "0123456789abcdef";
    std::string out = "\"";
    for (unsigned char c : value) {
        if (c == '"' || c == '\\') { out += '\\'; out += static_cast<char>(c); }
        else if (c < 0x20) {
            out += "\\u00"; out += hex[c >> 4]; out += hex[c & 15];
        } else out += static_cast<char>(c);
    }
    return out + '"';
}

std::string decode_key(std::string_view key) {
    auto hex = [](char c) -> int {
        if (c >= '0' && c <= '9') return c - '0';
        if (c >= 'a' && c <= 'f') return c - 'a' + 10;
        if (c >= 'A' && c <= 'F') return c - 'A' + 10;
        return -1;
    };
    std::string out;
    for (std::size_t i = 0; i < key.size(); ++i) {
        if (key[i] == '%' && i + 2 < key.size() &&
            hex(key[i + 1]) >= 0 && hex(key[i + 2]) >= 0) {
            out += static_cast<char>(hex(key[i + 1]) * 16 + hex(key[i + 2]));
            i += 2;
        } else out += key[i] == '+' ? ' ' : key[i];
    }
    return out;
}

// The core redactor handles plain query names. Also cover encoded names,
// userinfo and fragments, and fail closed for malformed provenance URLs.
std::string safe_url(const std::string& value, bool redact, const Redactor& redactor) {
    if (!redact || value.empty()) return value;
    try {
        auto url = parse_url(value);
        url.userinfo.clear();
        url.fragment.clear();
        url.has_fragment = false;
        std::string query;
        for (std::size_t start = 0; start < url.query.size();) {
            const auto end = url.query.find('&', start);
            const auto pair = url.query.substr(start, end == std::string::npos ? end : end - start);
            const auto eq = pair.find('=');
            const auto key = pair.substr(0, eq);
            if (!query.empty()) query += '&';
            query += redactor.is_sensitive_query_parameter(decode_key(key))
                ? key + "=" + redactor.policy().replacement : pair;
            if (end == std::string::npos) break;
            start = end + 1;
        }
        url.query = query;
        return url.to_string();
    } catch (...) { return redactor.policy().replacement; }
}

std::string method_name(std::string method) {
    for (char& c : method) if (c >= 'a' && c <= 'z') c = static_cast<char>(c - 'a' + 'A');
    return method.empty() ? "GET" : method;
}

std::string request_url(const DiscoveredEndpoint& ep) {
    if (ep.request_content_type == "application/x-www-form-urlencoded") return ep.url;
    auto url = parse_url(ep.url);
    std::vector<std::string> names;
    for (std::size_t start = 0; start < url.query.size();) {
        const auto end = url.query.find('&', start);
        const auto pair = url.query.substr(start, end == std::string::npos ? end : end - start);
        names.push_back(decode_key(pair.substr(0, pair.find('='))));
        if (end == std::string::npos) break;
        start = end + 1;
    }
    constexpr char hex[] = "0123456789ABCDEF";
    for (const auto& param : ep.parameters) {
        if (std::find(names.begin(), names.end(), param) != names.end()) continue;
        names.push_back(param);
        if (!url.query.empty()) url.query += '&';
        for (unsigned char c : param) {
            if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
                (c >= '0' && c <= '9') || c == '-' || c == '_' || c == '.' || c == '~')
                url.query += static_cast<char>(c);
            else { url.query += '%'; url.query += hex[c >> 4]; url.query += hex[c & 15]; }
        }
        url.query += '=';
        url.has_query = true;
    }
    return url.to_string();
}

Scrape2PostmanResult convert(scrape2oapi::Scrape2OapiResult source,
                            const Scrape2PostmanOptions& options, const Redactor& redactor) {
    Scrape2PostmanResult result;
    result.resolved = std::move(source.resolved);
    result.endpoints = std::move(source.endpoints);
    result.warnings = std::move(source.warnings);
    result.assistant_browser = std::move(source.assistant_browser);
    result.postman_json = render_postman_json(result.resolved, options, redactor);
    return result;
}
}  // namespace

std::string render_postman_json(const std::vector<ResolvedEndpoint>& resolved,
                               const Scrape2PostmanOptions& options, const Redactor& redactor) {
    std::ostringstream out;
    out.imbue(std::locale::classic());
    std::string collection_description =
        "Generated by ProwseTk scrape2postman. Heuristic API discoveries; "
        "not authoritative documentation. Request bodies and credentials are omitted.";
    if (options.assistant_browser_enabled) {
        collection_description += " Assistant browser handoff is enabled via ";
        collection_description += options.assistant_browser_method.empty()
            ? "webdriver" : options.assistant_browser_method;
        collection_description += "; any user-assisted coverage remains heuristic.";
    }
    out << "{\n  \"info\": {\"name\": " << quote(options.collection_name)
        << ", \"schema\": \"https://schema.getpostman.com/json/collection/v2.1.0/collection.json\","
        << " \"description\": " << quote(collection_description) << "},\n  \"item\": [";

    // Preserve distinct hosts and methods; deduplicate exact requests only.
    std::map<std::pair<std::string, std::string>, const ResolvedEndpoint*> ordered;
    for (const auto& r : resolved)
        ordered.try_emplace(std::make_pair(r.endpoint.url, method_name(r.endpoint.method)), &r);
    bool first = true;
    for (const auto& [key, record] : ordered) {
        const auto& ep = record->endpoint;
        const auto url = safe_url(request_url(ep), options.redact_secrets, redactor);
        const auto& method = key.second;
        if (!first) out << ',';
        first = false;
        std::ostringstream description;
        description.imbue(std::locale::classic());
        description << "Heuristic discovery; inferred request. Confidence: "
                    << (std::isfinite(ep.confidence) ? std::clamp(ep.confidence, 0.0, 1.0) : 0.0);
        if (options.include_provenance) {
            description << "\nSource: " << safe_url(ep.source, options.redact_secrets, redactor)
                        << "\nDiscovery method: " << ep.discovery_method;
            if (!record->final_url.empty())
                description << "\nFinal URL: " << safe_url(record->final_url, options.redact_secrets, redactor);
            for (const auto& hop : record->redirect_chain)
                description << "\nRedirect: " << safe_url(hop, options.redact_secrets, redactor);
            for (const auto& link : record->json_discovered)
                description << "\nJSON link: " << safe_url(link, options.redact_secrets, redactor);
            if (record->status != 0) description << "\nObserved HTTP status: " << record->status;
            // Exception messages and free-text notes can contain arbitrary secrets.
            if (!record->error.empty()) description << "\nResolution failed.";
        }
        out << "\n    {\"name\": " << quote(method + " " + url)
            << ", \"request\": {\"method\": " << quote(method)
            << ", \"url\": " << quote(url)
            << ", \"description\": " << quote(description.str()) << ", \"header\": [";
        if (!ep.request_content_type.empty())
            out << "{\"key\": \"Content-Type\", \"value\": " << quote(ep.request_content_type) << '}';
        out << ']';
        // Form field names are known, but private values were never captured.
        if (ep.request_content_type == "application/x-www-form-urlencoded") {
            out << ", \"body\": {\"mode\": \"urlencoded\", \"urlencoded\": [";
            bool first_field = true;
            for (const auto& param : ep.parameters) {
                if (!first_field) out << ',';
                first_field = false;
                out << "{\"key\": " << quote(param)
                    << ", \"value\": \"\", \"description\": \"Inferred field; supply a value\"}";
            }
            out << "]}";
        }
        out << "}, \"response\": []}";
    }
    out << "\n  ]\n}\n";
    return out.str();
}

void Scrape2PostmanResult::write_postman_json(const std::filesystem::path& path) const {
    std::ofstream file;
    file.exceptions(std::ios::failbit | std::ios::badbit);
    file.open(path, std::ios::binary | std::ios::trunc);
    file << postman_json;
    file.close();
}

Scrape2PostmanResult scrape_from_document(const Document& document,
    const Scrape2PostmanOptions& options, const Redactor& redactor) {
    return convert(scrape2oapi::scrape_from_document(document, options, redactor), options, redactor);
}

Scrape2PostmanResult scrape_from_session(Session& session, const Scrape2PostmanOptions& options) {
    return convert(scrape2oapi::scrape_from_session(session, options), options, Redactor());
}

Scrape2PostmanResult scrape(Session& session, const Scrape2PostmanOptions& options) {
    // Propagate navigation failure instead of exporting a stale page.
    if (!options.html.empty()) {
        auto base = options.base_url.empty() ? options.url : options.base_url;
        session.load_html(options.html, base.empty() ? "https://example.com/" : base);
    } else if (!options.url.empty()) session.navigate(options.url);
    return scrape_from_session(session, options);
}
}  // namespace prowsetk::plugins::scrape2postman
