prowsetk_add_library(prowsetk_gfx registry.cpp headless.cpp)
target_link_libraries(prowsetk_gfx PUBLIC ProwseTk::core)
set_target_properties(prowsetk_gfx PROPERTIES EXPORT_NAME gfx)
add_library(ProwseTk::gfx ALIAS prowsetk_gfx)
if(TARGET ProwseTk::gfx_x11)
    target_sources(prowsetk_gfx PRIVATE X11.cpp)
    target_link_libraries(prowsetk_gfx PRIVATE ProwseTk::gfx_x11)
    target_compile_definitions(prowsetk_gfx PRIVATE PROWSETK_GFX_HAVE_X11=1)
endif()
if(TARGET ProwseTk::gfx_fltk)
    target_sources(prowsetk_gfx PRIVATE FLTK.cpp)
    target_link_libraries(prowsetk_gfx PRIVATE ProwseTk::gfx_fltk)
    target_compile_definitions(prowsetk_gfx PRIVATE PROWSETK_GFX_HAVE_FLTK=1)
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        target_compile_definitions(prowsetk_gfx PRIVATE PROWSETK_GFX_FLTK_X11=1)
        target_link_libraries(prowsetk_gfx PRIVATE X11::X11)
    endif()
endif()
prowsetk_install_library(prowsetk_gfx)
