[project]
name = "booking-dotcom"
root = ".."

[[drivers]]
name = "booking-dotcom"
script = "examples/scrape_booking_dotcom.lua"
entrypoint = "main"
enabled = true
arguments = [
  { name = "output", type = "path", required = false },
  { name = "dotenv", type = "path", required = false },
  { name = "success_selector", type = "string", required = false },
  { name = "html", type = "string", required = false }
]
