if(PROWSETK_BUILD_COMPLEX_GUI)
    prowsetk_add_executable(prowse_gui main.cpp)
    target_link_libraries(prowse_gui PRIVATE ProwseTk::complex_gui)
    set_target_properties(prowse_gui PROPERTIES OUTPUT_NAME prowse-gui)
    if(UNIX AND NOT APPLE)
        set_target_properties(prowse_gui PROPERTIES INSTALL_RPATH
            "$ORIGIN/../${CMAKE_INSTALL_LIBDIR}/prowsetk/plugins;$ORIGIN/../${CMAKE_INSTALL_LIBDIR}")
    endif()
    install(TARGETS prowse_gui RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}")
endif()
install(FILES README.md example.html DESTINATION "${CMAKE_INSTALL_DATADIR}/prowsetk/prowse-gui")
