git submodule add https://github.com/c-ares/c-ares.git
git submodule add https://github.com/fmtlib/fmt.git
git submodule add https://github.com/google/gumbo-parser.git
git submodule add https://github.com/jemalloc/jemalloc.git
git submodule add https://github.com/pantor/inja.git
git submodule add https://github.com/satoren/kaguya.git
git submodule add https://github.com/lexbor/lexbor.git
git submodule add https://github.com/netsurf-browser/libdom.git
git submodule add https://github.com/enki/libev.git
git submodule add https://github.com/file/file.git
git submodule add https://github.com/sustrik/libmill.git
git submodule add https://github.com/nodejs/llhttp.git
git submodule add https://github.com/lua/lua.git
git submodule add https://github.com/Mbed-TLS/mbedtls.git
git submodule add https://github.com/cbodley/nexus.git
git submodule add https://github.com/zeux/pugixml.git
git submodule add https://github.com/quickjs-ng/quickjs.git
git submodule add https://github.com/google/re2.git
git submodule add https://github.com/simdjson/simdjson.git
git submodule add https://github.com/gabime/spdlog.git
git submodule add https://github.com/marzer/tomlplusplus.git
git submodule add https://github.com/uriparser/uriparser.git
git submodule add https://github.com/nodejs/uvwasi.git
git submodule add https://github.com/WebAssembly/wasi-libc.git
git submodule add https://github.com/WebAssembly/wasi-sdk.git
git submodule add https://github.com/bytecodealliance/wasmtime-cpp.git
git submodule add https://github.com/jbeder/yaml-cpp.git
git submodule add https://github.com/facebook/zstd.git
