#include "prowsetk/pdql.hpp"
#include "prowsetk/pdql.h"
#include <algorithm>
#include <cctype>
#include <cstdlib>
#include <regex>
#include <sstream>
#include <stdexcept>
namespace prowsetk::pdql {
namespace {
std::string trim(std::string s){ auto a=s.find_first_not_of(" \t\r\n"); if(a==s.npos)return {}; auto z=s.find_last_not_of(" \t\r\n"); return s.substr(a,z-a+1); }
std::string lower(std::string s){ for(char& c:s)c=(char)std::tolower((unsigned char)c); return s; }
std::string esc(std::string_view s){std::string o;for(char c:s){if(c=='&')o+="&amp;";else if(c=='<')o+="&lt;";else if(c=='>')o+="&gt;";else if(c=='\"')o+="&quot;";else o+=c;}return o;}
std::string json(std::string_view s){std::string o="\"";for(char c:s){if(c=='\\'||c=='\"')o+='\\';if(c=='\n')o+="\\n";else if(c=='\r')o+="\\r";else o+=c;}return o+'"';}
void descendants(const Node& n,std::vector<const Node*>& out){for(auto& c:n.children){out.push_back(c.get());descendants(*c,out);}}
std::string content(const Node& n){std::string s=n.text;for(auto& c:n.children)s+=content(*c);return trim(s);}
bool glob(std::string_view pattern,std::string_view value){size_t p=0,v=0,star=std::string_view::npos,mark=0;while(v<value.size()){if(p<pattern.size()&&(pattern[p]=='?'||pattern[p]==value[v])){++p;++v;}else if(p<pattern.size()&&pattern[p]=='*'){star=p++;mark=v;}else if(star!=pattern.npos){p=star+1;v=++mark;}else return false;}while(p<pattern.size()&&pattern[p]=='*')++p;return p==pattern.size();}
}
Document Document::parse(std::string_view html){Document d;d.root_=std::make_unique<Node>();d.root_->tag="#document";std::vector<Node*> stack{d.root_.get()};size_t i=0;while(i<html.size()){
 if(html.substr(i,4)=="<!--"){auto e=html.find("-->",i+4);i=e==html.npos?html.size():e+3;continue;}
 if(html[i]!='<'){size_t e=html.find('<',i);if(e==html.npos)e=html.size();stack.back()->text+=std::string(html.substr(i,e-i));i=e;continue;}
 if(i+1<html.size()&&html[i+1]=='!'){auto e=html.find('>',i+2);i=e==html.npos?html.size():e+1;continue;}
 bool closing=i+1<html.size()&&html[i+1]=='/';size_t a=i+(closing?2:1),e=html.find('>',a);if(e==html.npos){stack.back()->text+=html.substr(i);break;}std::string inside=trim(std::string(html.substr(a,e-a)));i=e+1;if(inside.empty())continue;
 if(closing){std::string tag=lower(inside.substr(0,inside.find_first_of(" \t/")));for(size_t k=stack.size();k>1;--k)if(stack[k-1]->tag==tag){stack.resize(k-1);break;}continue;}
 bool self=!inside.empty()&&inside.back()=='/';if(self)inside.pop_back();size_t q=inside.find_first_of(" \t\r\n");std::string tag=lower(inside.substr(0,q));if(tag.empty())continue;auto node=std::make_unique<Node>();node->tag=tag;node->parent=stack.back();std::string rest=q==inside.npos?"":inside.substr(q+1);size_t j=0;while(j<rest.size()){while(j<rest.size()&&std::isspace((unsigned char)rest[j]))++j;if(j==rest.size())break;size_t k=j;while(k<rest.size()&&!std::isspace((unsigned char)rest[k])&&rest[k]!='=')++k;std::string key=lower(rest.substr(j,k-j));j=k;while(j<rest.size()&&std::isspace((unsigned char)rest[j]))++j;std::string val="";if(j<rest.size()&&rest[j]=='='){++j;while(j<rest.size()&&std::isspace((unsigned char)rest[j]))++j;if(j<rest.size()&&(rest[j]=='\''||rest[j]=='\"')){char quote=rest[j++];size_t v=j;while(j<rest.size()&&rest[j]!=quote)++j;val=rest.substr(v,j-v);if(j<rest.size())++j;}else{size_t v=j;while(j<rest.size()&&!std::isspace((unsigned char)rest[j]))++j;val=rest.substr(v,j-v);}}if(!key.empty())node->attributes[key]=val;}
 Node* raw=node.get();stack.back()->children.push_back(std::move(node));if(!self&&tag!="br"&&tag!="img"&&tag!="hr"&&tag!="meta"&&tag!="input"&&tag!="link")stack.push_back(raw);
 }return d;}
Query::Query(std::string_view src){std::string s=trim(std::string(src));if(s.empty())throw std::invalid_argument("empty PDQL query");auto f=lower(s).find(" from ");if(f==std::string::npos){selector_=s;fields_="text";return;}auto first=lower(s).find("select ");fields_=trim(s.substr(first==0?7:0,f-(first==0?7:0)));std::string tail=trim(s.substr(f+6));auto w=lower(tail).find(" where ");if(w!=std::string::npos){where_=trim(tail.substr(w+7));tail=trim(tail.substr(0,w));}selector_=tail;if(selector_.empty())throw std::invalid_argument("missing selector");}
std::vector<Row> Query::execute(const Document& doc)const{std::string sel=trim(selector_);std::vector<const Node*> all;descendants(doc.root(),all);std::string tagpat="*",attr,attrval,rx;bool xpath=false,absolute=false;if(sel.rfind("xpath(",0)==0&&sel.back()==')'){xpath=true;sel=trim(sel.substr(6,sel.size()-7));if(sel.size()>=2&&(sel.front()=='\''||sel.front()=='\"'))sel=sel.substr(1,sel.size()-2);if(sel.rfind("//",0)==0)tagpat=sel.substr(2);else if(sel.size()>1&&sel[0]=='/') {absolute=true;tagpat=sel.substr(1);}auto at=tagpat.find("[@");if(at!=std::string::npos){auto end=tagpat.find(']',at);if(end!=std::string::npos){std::string pred=tagpat.substr(at+2,end-at-2);auto eq=pred.find('=');if(eq!=std::string::npos){attr=trim(pred.substr(0,eq));attrval=trim(pred.substr(eq+1));if(attrval.size()>1)attrval=attrval.substr(1,attrval.size()-2);}tagpat.resize(at);}}}
 auto rpos=sel.find("rx\"");if(rpos!=std::string::npos){auto end=sel.find('\"',rpos+3);if(end!=std::string::npos){rx=sel.substr(rpos+3,end-rpos-3);tagpat=trim(sel.substr(0,rpos));if(tagpat.empty())tagpat="*";}}
 if(!xpath){auto sp=tagpat.find_first_of(" \t");if(sp!=std::string::npos)tagpat.resize(sp);if(tagpat.empty())tagpat="*";}
 std::regex re; if(!rx.empty())try{re=std::regex(rx,std::regex::ECMAScript|std::regex::icase);}catch(...){throw std::invalid_argument("invalid rx predicate");}
 std::vector<const Node*> matches;for(auto*n:all){if(absolute&&n->parent!=&doc.root())continue;if(!glob(lower(tagpat),lower(n->tag)))continue;if(!attr.empty()){auto it=n->attributes.find(lower(attr));if(it==n->attributes.end()||it->second!=attrval)continue;}if(!rx.empty()&&!std::regex_search(content(*n),re))continue;matches.push_back(n);}
 if(!where_.empty()){auto eq=where_.find("==");std::string op="==";if(eq==std::string::npos){eq=where_.find('=');op="=";}if(eq!=std::string::npos){std::string key=trim(where_.substr(0,eq)),val=trim(where_.substr(eq+op.size()));if(val.size()>1&&(val.front()=='\''||val.front()=='\"'))val=val.substr(1,val.size()-2);matches.erase(std::remove_if(matches.begin(),matches.end(),[&](const Node*n){std::string got;if(key=="text")got=content(*n);else if(key=="tag")got=n->tag;else if(key.rfind("attr(",0)==0){auto a=key.find_first_of("\"'"),b=key.find_last_of("\"'");if(a!=std::string::npos&&b>a){auto it=n->attributes.find(key.substr(a+1,b-a-1));if(it!=n->attributes.end())got=it->second;}}return got!=val;}),matches.end());}}
 std::vector<std::string> cols;std::stringstream fs(fields_);for(std::string x;std::getline(fs,x,',');)cols.push_back(trim(x));if(cols.empty())cols.push_back("text");std::vector<Row> out;for(auto*n:matches){Row r;for(auto c:cols){auto lp=c.find('(');std::string name=c,kind=c,arg;if(lp!=std::string::npos){kind=trim(c.substr(0,lp));auto rp=c.find(')',lp);arg=rp==std::string::npos?"":trim(c.substr(lp+1,rp-lp-1));if(arg.size()>1&&(arg.front()=='\''||arg.front()=='\"'))arg=arg.substr(1,arg.size()-2);name=kind=="attr"?arg:kind;}if(kind=="text")r.fields[name]={content(*n),false};else if(kind=="tag")r.fields[name]={n->tag,false};else if(kind=="attr"){auto it=n->attributes.find(arg);r.fields[name]={it==n->attributes.end()?"":it->second,false};}else if(kind=="count")r.fields[name]={std::to_string(matches.size()),true};else if(kind=="number"){std::string t=content(*n);char*e=nullptr;double x=std::strtod(t.c_str(),&e);r.fields[name]={e==t.c_str()?"0":std::to_string(x),true};}else if(kind=="sum"||kind=="avg"){double sum=0;size_t count=0;for(auto*m:matches){std::string t=content(*m);char*e=nullptr;double x=std::strtod(t.c_str(),&e);if(e!=t.c_str()){sum+=x;++count;}}r.fields[name]={std::to_string(kind=="avg"&&count?sum/count:sum),true};}else r.fields[c]={content(*n),false};}out.push_back(std::move(r));}return out;}
std::string serialize(const std::vector<Row>& rows,Format f){std::ostringstream o;if(f==Format::Json){o<<"[";for(size_t i=0;i<rows.size();i++){if(i)o<<",";o<<"{";size_t j=0;for(auto&[k,v]:rows[i].fields){if(j++)o<<",";o<<json(k)<<":"<<(v.numeric?v.text:json(v.text));}o<<"}";}return o.str()+"]";}if(f==Format::Yaml){for(auto&r:rows){o<<"-";for(auto&[k,v]:r.fields)o<<"\n  "<<k<<": "<<(v.numeric?v.text:json(v.text));o<<"\n";}return o.str();}if(f==Format::SExpr){o<<"(";for(auto&r:rows){o<<"(";for(auto&[k,v]:r.fields)o<<"("<<k<<" "<<json(v.text)<<")";o<<")";}return o.str()+")";}o<<"<results>";for(auto&r:rows){o<<"<row>";for(auto&[k,v]:r.fields)o<<"<"<<k<<">"<<esc(v.text)<<"</"<<k<<">";o<<"</row>";}return o.str()+"</results>";}
}
struct pt_pdql_document{prowsetk::pdql::Document value;}; struct pt_pdql_query{prowsetk::pdql::Query* value;};struct pt_pdql_result{std::vector<prowsetk::pdql::Row> value;};
namespace {void seterr(char**e,const char*m){if(e){*e=(char*)std::malloc(std::strlen(m)+1);if(*e)std::strcpy(*e,m);}}}
#include <cstring>
extern "C" {
pt_pdql_document*pt_pdql_document_create(const char*h,char**e){if(e)*e=nullptr;try{if(!h)throw std::invalid_argument("null HTML");auto*d=new pt_pdql_document;d->value=prowsetk::pdql::Document::parse(h);return d;}catch(const std::exception&x){seterr(e,x.what());return nullptr;}}
void pt_pdql_document_free(pt_pdql_document*d){delete d;}
pt_pdql_node*pt_pdql_document_root(pt_pdql_document*d){return d?(pt_pdql_node*)&d->value.root():nullptr;}
size_t pt_pdql_node_child_count(const pt_pdql_node*n){return n?((const prowsetk::pdql::Node*)n)->children.size():0;}
pt_pdql_node*pt_pdql_node_child(const pt_pdql_node*n,size_t i){if(!n)return nullptr;auto&c=((const prowsetk::pdql::Node*)n)->children;return i<c.size()?(pt_pdql_node*)c[i].get():nullptr;}
const char*pt_pdql_node_tag(const pt_pdql_node*n){return n?((const prowsetk::pdql::Node*)n)->tag.c_str():nullptr;}
const char*pt_pdql_node_text(const pt_pdql_node*n){return n?((const prowsetk::pdql::Node*)n)->text.c_str():nullptr;}
const char*pt_pdql_node_attribute(const pt_pdql_node*n,const char*k){if(!n||!k)return nullptr;auto&i=((const prowsetk::pdql::Node*)n)->attributes;auto x=i.find(k);return x==i.end()?nullptr:x->second.c_str();}
pt_pdql_query*pt_pdql_query_compile(const char*s,char**e){if(e)*e=nullptr;try{if(!s)throw std::invalid_argument("null query");return new pt_pdql_query{new prowsetk::pdql::Query(s)};}catch(const std::exception&x){seterr(e,x.what());return nullptr;}}
void pt_pdql_query_free(pt_pdql_query*q){if(q){delete q->value;delete q;}}
pt_pdql_result*pt_pdql_query_execute(const pt_pdql_query*q,const pt_pdql_document*d,char**e){if(e)*e=nullptr;try{if(!q||!d)throw std::invalid_argument("null query or document");return new pt_pdql_result{q->value->execute(d->value)};}catch(const std::exception&x){seterr(e,x.what());return nullptr;}}
char*pt_pdql_result_serialize(const pt_pdql_result*r,pt_pdql_format f,char**e){if(e)*e=nullptr;try{if(!r)throw std::invalid_argument("null result");if(f<PT_PDQL_JSON||f>PT_PDQL_SEXPR)throw std::invalid_argument("invalid format");auto s=prowsetk::pdql::serialize(r->value,(prowsetk::pdql::Format)f);char*p=(char*)std::malloc(s.size()+1);if(!p)throw std::bad_alloc();std::memcpy(p,s.c_str(),s.size()+1);return p;}catch(const std::exception&x){seterr(e,x.what());return nullptr;}}
void pt_pdql_result_free(pt_pdql_result*r){delete r;}void pt_pdql_str_free(char*s){std::free(s);}
}
