add_subdirectory(page2pdf)
add_subdirectory(page2latex)
add_subdirectory(prowse-tui)
if(UNIX AND PROWSETK_HAVE_LUA AND PROWSETK_HAVE_TOMLPLUSPLUS)
    add_subdirectory(automation)
    add_subdirectory(crawler)
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        add_subdirectory(pagewatch)
    endif()
endif()
